# .github/workflows/automerge.yml

name: Auto-Merge Pull Requests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  schedule:
    # Run every 30 minutes
    - cron: '*/30 * * * *'

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write           # Needed to push merge commits
      pull-requests: write      # Needed to merge pull requests

    steps:
      - name: Auto-merge new pull requests
        if: github.event_name == 'pull_request_target'
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: true
          merge-method: merge
          remove-branch: true
          conflict-check: true
          required-statuses: []  # Leave empty to require all checks

      - name: Auto-merge existing pull requests (scheduled)
        if: github.event_name == 'schedule'
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-requests-filter: open
          merge-method: merge
          remove-branch: true
          conflict-check: true
          required-statuses: []  # Leave empty to require all checks
