# .github/workflows/automerge.yml

name: Auto-Merge Pull Requests

on:
  workflow_dispatch:          # Allows manual run
  pull_request_target:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '*/30 * * * *'    # Every 30 minutes

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Auto-merge new pull requests
        if: github.event_name == 'pull_request_target'
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: true
          merge-method: merge
          remove-branch: true
          conflict-check: true
          required-statuses: ""   # ✅ Fixed

      - name: Auto-merge existing pull requests (scheduled)
        if: github.event_name == 'schedule'
        uses: pascalgn/automerge-action@v0.16.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pull-requests-filter: open
          merge-method: merge
          remove-branch: true
          conflict-check: true
          required-statuses: ""   # ✅ Fixed
